# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: cache gradle caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/gradle.properties', '**/build.gradle.kts', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: cache loom
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/gradle.properties', '**/build.gradle.kts', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/versions/

  cleanup-caches:
    runs-on: ubuntu-24.04
    needs: build
    if: always()
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: cleanup old caches
        run: |
          gh extension install actions/gh-actions-cache
          
          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          
          CURRENT_LOOM_KEY="${{ runner.os }}-loom-${{ hashFiles('**/gradle.properties', '**/build.gradle.kts', '**/settings.gradle.kts') }}"
          CURRENT_GRADLE_KEY="${{ runner.os }}-gradle-caches-${{ hashFiles('**/gradle.properties', '**/build.gradle.kts', '**/settings.gradle.kts') }}"
          CURRENT_WRAPPER_KEY="${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}"
          
          # Cleanup old loom caches (across all branches)
          echo "Fetching list of loom cache keys across all branches"
          cacheKeys=$(gh actions-cache list -R $REPO --key "${{ runner.os }}-loom-" | cut -f 1)
          echo "Deleting old loom caches..."
          for cacheKey in $cacheKeys
          do
              if [ "$cacheKey" != "$CURRENT_LOOM_KEY" ]; then
                  gh actions-cache delete $cacheKey -R $REPO --confirm
              fi
          done
          
          # Cleanup old gradle caches (across all branches)
          echo "Fetching list of gradle cache keys across all branches"
          cacheKeys=$(gh actions-cache list -R $REPO --key "${{ runner.os }}-gradle-caches-" | cut -f 1)
          echo "Deleting old gradle caches..."
          for cacheKey in $cacheKeys
          do
              if [ "$cacheKey" != "$CURRENT_GRADLE_KEY" ]; then
                  gh actions-cache delete $cacheKey -R $REPO --confirm
              fi
          done
          
          # Cleanup old wrapper caches (across all branches)
          echo "Fetching list of wrapper cache keys across all branches"
          cacheKeys=$(gh actions-cache list -R $REPO --key "${{ runner.os }}-gradle-wrapper-" | cut -f 1)
          echo "Deleting old wrapper caches..."
          for cacheKey in $cacheKeys
          do
              if [ "$cacheKey" != "$CURRENT_WRAPPER_KEY" ]; then
                  gh actions-cache delete $cacheKey -R $REPO --confirm
              fi
          done
          
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        continue-on-error: true
